config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'productos', 'action' => 'index', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Movimiento.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Movimiento Entity
 *
 * @property int $id
 * @property \Cake\I18n\Time $fecha
 * @property string $documentos
 * @property string $tipo
 * @property int $cantidad
 * @property int $existencia
 * @property float $precio_medio
 * @property float $subtotal
 * @property string $saldo
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 * @property int $productos_id
 *
 * @property \App\Model\Entity\Producto $producto
 */
class Movimiento extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Table/MovimientosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Movimientos Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Productos
 *
 * @method \App\Model\Entity\Movimiento get($primaryKey, $options = [])
 * @method \App\Model\Entity\Movimiento newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Movimiento[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Movimiento|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Movimiento patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Movimiento[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Movimiento findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class MovimientosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('movimientos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Productos', [
            'foreignKey' => 'productos_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->date('fecha')
            ->requirePresence('fecha', 'create')
            ->notEmpty('fecha');

        $validator
            ->integer('folio')
            ->requirePresence('folio', 'create')
            ->notEmpty('folio');

        $validator
            ->requirePresence('documentos', 'create')
            ->notEmpty('documentos');

        $validator
            ->requirePresence('tipo', 'create')
            ->notEmpty('tipo')
            ->add('tipo', 'inList', [
                  'rule' => ['inList', ['e', 's']],
                  'message' => 'tipo no valido'
                  ]);

        $validator
            ->integer('cantidad')
            ->allowEmpty('cantidad');

        $validator
            ->integer('existencia')
            ->requirePresence('existencia', 'create')
            ->notEmpty('existencia');

        $validator
            ->decimal('precio_medio')
            ->requirePresence('precio_medio', 'create')
            ->notEmpty('precio_medio');

        $validator
            ->decimal('subtotal')
            ->requirePresence('subtotal', 'create')
            ->notEmpty('subtotal');

        $validator
            ->allowEmpty('saldo');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['productos_id'], 'Productos'));

        return $rules;
    }

    public function findLastMovimiento(Query $query, array $options)
    {
        $id = $options['id'];
        return $query->where(['productos_id' => $id])->order(['created'=>'DESC'])->first();
    }
}

src/Model/Table/ProductosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Productos Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Partidas
 * @property \Cake\ORM\Association\BelongsTo $Almacenes
 *
 * @method \App\Model\Entity\Producto get($primaryKey, $options = [])
 * @method \App\Model\Entity\Producto newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Producto[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Producto|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Producto patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Producto[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Producto findOrCreate($search, callable $callback = null, $options = [])
 */
class ProductosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('productos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Partidas', [
            'foreignKey' => 'partidas_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Almacenes', [
            'foreignKey' => 'almacenes_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Movimientos', [
            'foreignKey' => 'productos_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('nombre', 'create')
            ->notEmpty('nombre');

        $validator
            ->requirePresence('clave', 'create')
            ->notEmpty('clave');

        $validator
            ->requirePresence('presentacion', 'create')
            ->notEmpty('presentacion');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['partidas_id'], 'Partidas'));
        $rules->add($rules->existsIn(['almacenes_id'], 'Almacenes'));

        return $rules;
    }
}

src/Controller/MovimientosController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Movimientos Controller
 *
 * @property \App\Model\Table\MovimientosTable $Movimientos
 */
class MovimientosController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Productos']
        ];
        $movimientos = $this->paginate($this->Movimientos);

        $this->set(compact('movimientos'));
        $this->set('_serialize', ['movimientos']);
    }

    /**
     * View method
     *
     * @param string|null $id Movimiento id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $movimiento = $this->Movimientos->get($id, [
            'contain' => ['Productos']
        ]);

        $this->set('movimiento', $movimiento);
        $this->set('_serialize', ['movimiento']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($id = null, $tipo = null)
    {
        $movimiento = $this->Movimientos->newEntity();
        if ($this->request->is('post')) {
            $movimiento = $this->Movimientos->patchEntity($movimiento, $this->request->getData());
            if ($this->Movimientos->save($movimiento)) {
                $this->Flash->success(__('El movimiento se guardo con exito.'));

                return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
            }else{
                $this->Flash->error(__('No se pudo guardar el movimiento, por favor intenelo de nuevo'));
                return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
          }
        }
        if (is_null($tipo) || is_null($id)) {
          $this->Flash->error(__('Tipo de movimiento no seleccionado'));
          return $this->redirect($this->referer());
        }
        $ultimoMovimiento=$this->Movimientos->find('lastMovimiento', ['id'=>$id]);
        switch ($tipo) {
          case 'entrada':
            $this->set(compact('id','ultimoMovimiento'));
            return $this->render('entrada');
            break;

          case 'salida':
            $this->set(compact('id','ultimoMovimiento'));
            return $this->render('salida');
            break;

          deault:
            $this->Flash->error(__('No se pudo guardar el movimiento, por favor intenelo de nuevo'));
            return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
            break;
        }
        $productos = $this->Movimientos->Productos->find('list', ['limit' => 200]);
        $this->set(compact('movimiento', 'productos'));
        $this->set('_serialize', ['movimiento']);
    }


    /**
     * Edit method
     *
     * @param string|null $id Movimiento id.
     * @return \Cake\Network\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $movimiento = $this->Movimientos->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $movimiento = $this->Movimientos->patchEntity($movimiento, $this->request->getData());
            if ($this->Movimientos->save($movimiento)) {
                $this->Flash->success(__('Se ha modificado el movimiento'));

                return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
            }
            $this->Flash->error(__('No se pudo modificar el movimiento'));
        }
        $productos = $this->Movimientos->Productos->find('list', ['limit' => 200]);
        $this->set(compact('movimiento', 'productos'));
        $this->set('_serialize', ['movimiento']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Movimiento id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $movimiento = $this->Movimientos->get($id);
        if ($this->Movimientos->delete($movimiento)) {
            $this->Flash->success(__('El movimiento se ha eliminado'));
            return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
        } else {
            $this->Flash->error(__('El movimiento no se pudo eliminar'));
            return $this->redirect(['controller'=>'Productos','action' => 'view', $movimiento->productos_id]);
        }

        return $this->redirect(['action' => 'index']);
    }


    public function findByFolio()
    {
        if ($this->request->is(['post'])) {
          $folio=$this->request->getData('folio');
          $tipo=$this->request->getData('tipo');
          $movimientos=$this->Movimientos->find('all')
              ->where(['folio'=>$folio])
              ->where(['tipo'=>$tipo])
              ->contain(['Productos','Productos.Partidas']);
          $this->set(compact('movimientos','tipo','folio'));
          return $this->render('viewByFolio');
        }

    }

    public function isAuthorized($user)
    {

        return true;
    }
}

src/Template/Movimientos/add.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Movimientos'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Productos'), ['controller' => 'Productos', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Producto'), ['controller' => 'Productos', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="movimientos form large-9 medium-8 columns content">
    <?= $this->Form->create($movimiento) ?>
    <fieldset>
        <legend><?= __('Add Movimiento') ?></legend>
        <?php
            echo $this->Form->control('fecha');
            echo $this->Form->control('documentos');
            echo $this->Form->control('tipo');
            echo $this->Form->control('cantidad');
            echo $this->Form->control('existencia');
            echo $this->Form->control('precio_medio');
            echo $this->Form->control('subtotal');
            echo $this->Form->control('saldo');
            echo $this->Form->control('productos_id', ['options' => $productos]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Movimientos/edit.ctp
<div class="col-md-9">
    <div class="panel panel-default">
    <div class="panel-body">
      <form class="form-horizontal" method="post" accept-charset="utf-8" action="<?= $this->Url->build(["controller"=>"movimientos","action"=>"edit",$movimiento->id])?>">
        <fieldset>
          <legend>Editar movimiento</legend>
          <div class="form-group">
            <label for="fecha" class="col-lg-2 control-label">Fecha</label>
            <div class="col-lg-4">
              <input type="date" name="fecha" required="required" maxlength="255" id="fecha" class="form-control" value="<?=$movimiento->fecha->format('Y-m-d')?>">
            </div>
          </div>
          <div class="form-group">
            <label for="folio" class="col-lg-2 control-label">Folio</label>
            <div class="col-lg-10">
              <input type="number" name="folio" required="required" maxlength="6" id="folio" class="form-control" value="<?=$movimiento->folio?>">
            </div>
          </div>
          <div class="form-group">
            <label for="documentos" class="col-lg-2 control-label">Documentos</label>
            <div class="col-lg-10">
              <input type="text" name="documentos" required="required" maxlength="255" id="documentos" class="form-control" value="<?=$movimiento->documentos?>">
            </div>
          </div>
          <div class="form-group">
            <label for="documentos" class="col-lg-2 control-label">Tipo de Movimiento</label>
            <div class="col-lg-10">
              <select class="form-control" name="tipo">
                <option value="e" <?php if($movimiento->tipo === 'e'){ echo'selected="true"';}?> >Entrada</option>
                <option value="s" <?php if($movimiento->tipo === 's'){ echo'selected="true"';}?> >Salida</option>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label for="cantidad" class="col-lg-2 control-label">Cantidad</label>
            <div class="col-lg-10">
              <input type="number" name="cantidad" class="form-control" id="cantidad" required="required" value="<?=$movimiento->cantidad?>">
            </div>
          </div>
          <div class="form-group">
            <label for="precio_medio" class="col-lg-2 control-label">Precio Medio</label>
            <div class="col-lg-10">
              <input type="number" name="precio_medio" required="required" step=".00001" id="precio_medio" class="form-control" value="<?=$movimiento->precio_medio?>" min=".00001">
            </div>
          </div>
          <div class="form-group">
            <label for="existencia" class="col-lg-2 control-label">Existencia</label>
            <div class="col-lg-10">
              <input type="number" name="existencia" required="required" id="existencia" class="form-control" value="<?=$movimiento->existencia?>">
            </div>
          </div>
          <div class="form-group">
            <label for="subtotal" class="col-lg-2 control-label">Debe</label>
            <div class="col-lg-10">
              <input type="number" name="subtotal" required="required" step=".00001" id="subtotal" class="form-control" value="<?=$movimiento->subtotal?>" >
            </div>
          </div>
          <div class="form-group">
            <label for="saldo" class="col-lg-2 control-label">Subtotal</label>
            <div class="col-lg-10">
              <input type="number" name="saldo" required="required" step=".00001" id="saldo" class="form-control" value="<?=$movimiento->saldo?>">
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
              <a href="<?= $this->Url->build(["controller"=>"productos", "action"=>"view", $movimiento->productos_id])?>"  class="btn btn-default">Cancelar</a>
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>



<?php $this->append('scripts');?>
  <script type="text/javascript">
  $(document).ready(function() {
    $('#cantidad').keyup(calcular);
    $('#precio_medio').keyup(calcular);
    } );

    function calcular() {
      $('#subtotal').val(parseFloat($('#cantidad').val()) * parseFloat($('#precio_medio').val()));
    }
  </script>
<?php $this->end();?>

src/Template/Movimientos/entrada.ctp
<div class="col-md-9 ">
    <div class="panel panel-default">
    <div class="panel-body">
      <form class="form-horizontal" method="post" accept-charset="utf-8" action="<?= $this->Url->build(["controller"=>"movimientos","action"=>"add"])?>">
        <fieldset>
          <legend>Nueva Entrada</legend>
          <div class="form-group">
            <label for="fecha" class="col-lg-2 control-label">Fecha</label>
            <div class="col-lg-4">
              <input type="date" name="fecha" required="required" maxlength="255" id="fecha" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="folio" class="col-lg-2 control-label">Folio</label>
            <div class="col-lg-10">
              <input type="number" name="folio" required="required" maxlength="6" id="folio" class="form-control" placeholder="000000">
            </div>
          </div>
          <div class="form-group">
            <label for="documentos" class="col-lg-2 control-label">Documentos de Procedencia</label>
            <div class="col-lg-10">
              <input type="text" name="documentos" required="required" maxlength="255" id="documentos" class="form-control" placeholder="Documentos">
            </div>
          </div>
          <!-- Definir el tipo de movimiento, en este caso, Entrada = e -->
          <input type="text" name="tipo" value="e" hidden="true">
          <div class="form-group">
            <label for="cantidad" class="col-lg-2 control-label">Cantidad</label>
            <div class="col-lg-10">
              <input type="number" name="cantidad" class="form-control" id="cantidad" required="required" >
            </div>
          </div>
          <div class="form-group">
            <label for="precio_medio" class="col-lg-2 control-label">Precio Medio</label>
            <div class="col-lg-10">
              <input type="number" name="precio_medio" required="required" step=".00001" id="precio_medio" class="form-control" value="0" min=".00001">
            </div>
          </div>
          <div class="form-group">
            <label for="existencia" class="col-lg-2 control-label">Existencia</label>
            <div class="col-lg-10">
              <input type="number" name="existencia" required="required" id="existencia" class="form-control" value="<?=is_null($ultimoMovimiento)?'' :$ultimoMovimiento->existencia?>">
            </div>
          </div>
          <div class="form-group">
            <label for="subtotal" class="col-lg-2 control-label">Debe</label>
            <div class="col-lg-10">
              <input type="number" name="subtotal" required="required" step=".00001" id="subtotal" class="form-control" >
            </div>
          </div>
          <div class="form-group">
            <label for="saldo" class="col-lg-2 control-label">Saldo</label>
            <div class="col-lg-10">
              <input type="number" name="saldo" required="required" step=".00001" id="saldo" class="form-control" value="0">
            </div>
          </div>
          <input type="number" name="productos_id" value="<?=$id?>" hidden="true">
          <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
              <a href="<?= $this->Url->build(["controller"=>"productos", "action"=>"view", $id])?>"  class="btn btn-default">Cancelar</a>
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>

<div class="col-md-3">
    <div class="well">
        <h4>Ultimo Movimiento:</h4>
        <?php if(is_null($ultimoMovimiento)):?>
          <div class="row">
            <div class="alert alert-danger" role="alert">Este Producto no tiene movimientos</div>
          </div>
        <?php else:?>
          <div class="form-group">
            <label>Tipo de movimiento:</label>
            <span ><?=$ultimoMovimiento->tipo==='e'?'Entrada':'Salida'?></span>
          </div>
          <div class="form-group">
            <label>Fecha del movimiento:</label>
            <span ><?=$ultimoMovimiento->fecha->format('d-m-y')?></span>
          </div>
          <div class="form-group">
            <label>Cantidad:</label>
            <span ><?=$ultimoMovimiento->cantidad?></span>
          </div>
          <div class="form-group">
            <label>Existencia:</label>
            <span ><?=$ultimoMovimiento->existencia?></span>
          </div>
          <div class="form-group">
            <label>Precio medio:</label>
            <span ><?=$ultimoMovimiento->precio_medio?></span>
          </div>
          <div class="form-group">
            <label>Saldo:</label>
            <span ><?=$ultimoMovimiento->saldo?></span>
          </div>
        <?php endif;?>
    </div>

</div>

<?php $this->append('scripts');?>
  <script type="text/javascript">
  $(document).ready(function() {
    $('#cantidad').keyup(calcular);
    $('#subtotal').keyup(calcular);
    } );

    function calcular() {
      $('#existencia').val(parseFloat(<?=is_null($ultimoMovimiento)?0 :$ultimoMovimiento->existencia?>) + parseFloat($('#cantidad').val()));
      $('#precio_medio').val( (parseFloat(<?=is_null($ultimoMovimiento)?0 :$ultimoMovimiento->saldo?>) + parseFloat($('#subtotal').val())) / parseFloat($('#existencia').val()) )
      $('#saldo').val(parseFloat($('#existencia').val()) * parseFloat($('#precio_medio').val()));
    }
  </script>
<?php $this->end();?>

src/Template/Movimientos/view_by_folio.ctp
<div class="row">
  <div class="col-md-8">
      <div class="panel panel-default">
      <div class="panel-body">
        <form class="form-horizontal" method="post" accept-charset="utf-8" action="<?= $this->Url->build(["controller"=>"movimientos","action"=>"findByFolio"])?>" enctype="multipart/form-data">
          <fieldset>
            <legend>Buscar Folios</legend>
            <div class="form-group">
              <label for="folio" class="col-lg-2 control-label">Folio</label>
              <div class="col-lg-10">
                <input type="number" name="folio" required="required" maxlength="6" id="folio" class="form-control" placeholder="000000">
              </div>
            </div>
            <div class="form-group">
              <label for="tipo" class="col-lg-2 control-label">Tipo de Movimientos</label>
              <div class="col-lg-10">
                <select class="form-control" name="tipo">
                  <option value="e">Entradas</option>
                  <option value="s">Salidas</option>
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Buscar</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h4>Folio <?=$folio?>, <?=$tipo==='e'?'Entradas':'Salidas'?></h4>
    </div>
      <!-- /.panel-heading -->
      <div class="panel-body">

          <table width="100%" class="table table-striped table-bordered table-hover" id="productos">
              <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Documentos</th>
                    <th>Articulos</th>
                    <th>Partida</th>
                    <th>Presentación</th>
                    <th>Unidad</th>
                    <th>Precio</th>
                    <th>Importe</th>
                  </tr>
              </thead>
              <tbody>
                <?php foreach ($movimientos as $movimiento): ?>
                  <tr>
                    <td ><?= h($movimiento->fecha->format('d-m-y')) ?></td>
                    <td ><?= h($movimiento->documentos) ?></td>
                    <td ><?= h($movimiento->producto->nombre) ?></td>
                    <td ><?= $movimiento->producto->partida->nombre?></td>
                    <td ><?=$movimiento->producto->presentacion?></td>
                    <td><?=$movimiento->cantidad?></td>
                    <td>$<?=$movimiento->precio_medio?></td>
                    <td >$<?=$movimiento->subtotal ?></td>
                  </tr>
                <?php endforeach; ?>
              </tbody>
          </table>
          <!-- /.table-responsive -->

      </div>
      <!-- /.panel-body -->
  </div>
</div>

<?php $this->append('libraries');?>
  <?= $this->Html->script(['moment.min','datetime-moment','dataTables.buttons.min','buttons.flash.min','buttons.html5.min','jszip.min'])?>
  <?= $this->Html->css(['buttons.dataTables.min'])?>
<?php $this->end();?>

<?php $this->append('scripts');?>
  <script type="text/javascript">
  $(document).ready(function() {
    $.fn.dataTable.moment( 'DD-MM-YY' );
      $('#productos').DataTable({
        "dom": '<"col-sm-12 pull-left"fl>rt<"bottom"ip><"clear">',
        dom: 'Bfrtip',
        pageLength: 50,
        buttons: [
          {
              extend: 'excelHtml5',
              title: `Folio <?=$folio?>`,
              exportOptions: {columns: [ 0, 1, 2, 3, 4, 5, 6, 7 ]}
          }
        ]
      });
    } );
  </script>
<?php $this->end();?>